*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 21.03.2022 at 15:15:36
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZUBME_V005......................................*
FORM GET_DATA_ZUBME_V005.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZUBME_T005 WHERE
(VIM_WHERETAB) .
    CLEAR ZUBME_V005 .
ZUBME_V005-MANDT =
ZUBME_T005-MANDT .
ZUBME_V005-PLANT =
ZUBME_T005-PLANT .
ZUBME_V005-PROJECT_TYPE =
ZUBME_T005-PROJECT_TYPE .
ZUBME_V005-PROCESS_CODE =
ZUBME_T005-PROCESS_CODE .
ZUBME_V005-ERROR_CODE =
ZUBME_T005-ERROR_CODE .
ZUBME_V005-TYPE =
ZUBME_T005-TYPE .
    SELECT SINGLE * FROM ZUBME_T005T WHERE
PLANT = ZUBME_T005-PLANT AND
PROJECT_TYPE = ZUBME_T005-PROJECT_TYPE AND
PROCESS_CODE = ZUBME_T005-PROCESS_CODE AND
ERROR_CODE = ZUBME_T005-ERROR_CODE AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZUBME_V005-ERROR_CODE_TEXT =
ZUBME_T005T-ERROR_CODE_TEXT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZUBME_V005.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZUBME_V005 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZUBME_V005.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZUBME_V005-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZUBME_T005 WHERE
  PLANT = ZUBME_V005-PLANT AND
  PROJECT_TYPE = ZUBME_V005-PROJECT_TYPE AND
  PROCESS_CODE = ZUBME_V005-PROCESS_CODE AND
  ERROR_CODE = ZUBME_V005-ERROR_CODE .
    IF SY-SUBRC = 0.
    DELETE ZUBME_T005 .
    ENDIF.
    DELETE FROM ZUBME_T005T WHERE
    PLANT = ZUBME_T005-PLANT AND
    PROJECT_TYPE = ZUBME_T005-PROJECT_TYPE AND
    PROCESS_CODE = ZUBME_T005-PROCESS_CODE AND
    ERROR_CODE = ZUBME_T005-ERROR_CODE .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZUBME_T005 WHERE
  PLANT = ZUBME_V005-PLANT AND
  PROJECT_TYPE = ZUBME_V005-PROJECT_TYPE AND
  PROCESS_CODE = ZUBME_V005-PROCESS_CODE AND
  ERROR_CODE = ZUBME_V005-ERROR_CODE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZUBME_T005.
    ENDIF.
ZUBME_T005-MANDT =
ZUBME_V005-MANDT .
ZUBME_T005-PLANT =
ZUBME_V005-PLANT .
ZUBME_T005-PROJECT_TYPE =
ZUBME_V005-PROJECT_TYPE .
ZUBME_T005-PROCESS_CODE =
ZUBME_V005-PROCESS_CODE .
ZUBME_T005-ERROR_CODE =
ZUBME_V005-ERROR_CODE .
ZUBME_T005-TYPE =
ZUBME_V005-TYPE .
    IF SY-SUBRC = 0.
    UPDATE ZUBME_T005 ##WARN_OK.
    ELSE.
    INSERT ZUBME_T005 .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZUBME_T005T WHERE
    PLANT = ZUBME_T005-PLANT AND
    PROJECT_TYPE = ZUBME_T005-PROJECT_TYPE AND
    PROCESS_CODE = ZUBME_T005-PROCESS_CODE AND
    ERROR_CODE = ZUBME_T005-ERROR_CODE AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZUBME_T005T.
ZUBME_T005T-PLANT =
ZUBME_T005-PLANT .
ZUBME_T005T-PROJECT_TYPE =
ZUBME_T005-PROJECT_TYPE .
ZUBME_T005T-PROCESS_CODE =
ZUBME_T005-PROCESS_CODE .
ZUBME_T005T-ERROR_CODE =
ZUBME_T005-ERROR_CODE .
ZUBME_T005T-SPRAS =
SY-LANGU .
      ENDIF.
ZUBME_T005T-ERROR_CODE_TEXT =
ZUBME_V005-ERROR_CODE_TEXT .
    IF SY-SUBRC = 0.
    UPDATE ZUBME_T005T ##WARN_OK.
    ELSE.
    INSERT ZUBME_T005T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZUBME_V005-UPD_FLAG,
STATUS_ZUBME_V005-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZUBME_V005.
  SELECT SINGLE * FROM ZUBME_T005 WHERE
PLANT = ZUBME_V005-PLANT AND
PROJECT_TYPE = ZUBME_V005-PROJECT_TYPE AND
PROCESS_CODE = ZUBME_V005-PROCESS_CODE AND
ERROR_CODE = ZUBME_V005-ERROR_CODE .
ZUBME_V005-MANDT =
ZUBME_T005-MANDT .
ZUBME_V005-PLANT =
ZUBME_T005-PLANT .
ZUBME_V005-PROJECT_TYPE =
ZUBME_T005-PROJECT_TYPE .
ZUBME_V005-PROCESS_CODE =
ZUBME_T005-PROCESS_CODE .
ZUBME_V005-ERROR_CODE =
ZUBME_T005-ERROR_CODE .
ZUBME_V005-TYPE =
ZUBME_T005-TYPE .
    SELECT SINGLE * FROM ZUBME_T005T WHERE
PLANT = ZUBME_T005-PLANT AND
PROJECT_TYPE = ZUBME_T005-PROJECT_TYPE AND
PROCESS_CODE = ZUBME_T005-PROCESS_CODE AND
ERROR_CODE = ZUBME_T005-ERROR_CODE AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZUBME_V005-ERROR_CODE_TEXT =
ZUBME_T005T-ERROR_CODE_TEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZUBME_V005-ERROR_CODE_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZUBME_V005 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZUBME_V005-PLANT TO
ZUBME_T005-PLANT .
MOVE ZUBME_V005-PROJECT_TYPE TO
ZUBME_T005-PROJECT_TYPE .
MOVE ZUBME_V005-PROCESS_CODE TO
ZUBME_T005-PROCESS_CODE .
MOVE ZUBME_V005-ERROR_CODE TO
ZUBME_T005-ERROR_CODE .
MOVE ZUBME_V005-MANDT TO
ZUBME_T005-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZUBME_T005'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZUBME_T005 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZUBME_T005'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZUBME_T005-PLANT TO
ZUBME_T005T-PLANT .
MOVE ZUBME_T005-PROJECT_TYPE TO
ZUBME_T005T-PROJECT_TYPE .
MOVE ZUBME_T005-PROCESS_CODE TO
ZUBME_T005T-PROCESS_CODE .
MOVE ZUBME_T005-ERROR_CODE TO
ZUBME_T005T-ERROR_CODE .
MOVE SY-LANGU TO
ZUBME_T005T-SPRAS .
MOVE ZUBME_V005-MANDT TO
ZUBME_T005T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZUBME_T005T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZUBME_T005T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZUBME_T005T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
