*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 23.02.2022 at 15:35:59
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZUBME_V007......................................*
FORM GET_DATA_ZUBME_V007.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZUBME_T007 WHERE
(VIM_WHERETAB) .
    CLEAR ZUBME_V007 .
ZUBME_V007-MANDT =
ZUBME_T007-MANDT .
ZUBME_V007-WERKS =
ZUBME_T007-WERKS .
ZUBME_V007-PROJECT_TYPE =
ZUBME_T007-PROJECT_TYPE .
ZUBME_V007-PROCESS_CODE =
ZUBME_T007-PROCESS_CODE .
ZUBME_V007-ERROR_CODE =
ZUBME_T007-ERROR_CODE .
ZUBME_V007-FROM_TO =
ZUBME_T007-FROM_TO .
ZUBME_V007-CC_RECEIVERS =
ZUBME_T007-CC_RECEIVERS .
ZUBME_V007-REC_RECEIVERS =
ZUBME_T007-REC_RECEIVERS .
ZUBME_V007-SO10_TEXT_NAME =
ZUBME_T007-SO10_TEXT_NAME .
<VIM_TOTAL_STRUC> = ZUBME_V007.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZUBME_V007 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZUBME_V007.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZUBME_V007-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZUBME_T007 WHERE
  WERKS = ZUBME_V007-WERKS AND
  PROJECT_TYPE = ZUBME_V007-PROJECT_TYPE AND
  PROCESS_CODE = ZUBME_V007-PROCESS_CODE AND
  ERROR_CODE = ZUBME_V007-ERROR_CODE .
    IF SY-SUBRC = 0.
    DELETE ZUBME_T007 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZUBME_T007 WHERE
  WERKS = ZUBME_V007-WERKS AND
  PROJECT_TYPE = ZUBME_V007-PROJECT_TYPE AND
  PROCESS_CODE = ZUBME_V007-PROCESS_CODE AND
  ERROR_CODE = ZUBME_V007-ERROR_CODE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZUBME_T007.
    ENDIF.
ZUBME_T007-MANDT =
ZUBME_V007-MANDT .
ZUBME_T007-WERKS =
ZUBME_V007-WERKS .
ZUBME_T007-PROJECT_TYPE =
ZUBME_V007-PROJECT_TYPE .
ZUBME_T007-PROCESS_CODE =
ZUBME_V007-PROCESS_CODE .
ZUBME_T007-ERROR_CODE =
ZUBME_V007-ERROR_CODE .
ZUBME_T007-FROM_TO =
ZUBME_V007-FROM_TO .
ZUBME_T007-CC_RECEIVERS =
ZUBME_V007-CC_RECEIVERS .
ZUBME_T007-REC_RECEIVERS =
ZUBME_V007-REC_RECEIVERS .
ZUBME_T007-SO10_TEXT_NAME =
ZUBME_V007-SO10_TEXT_NAME .
    IF SY-SUBRC = 0.
    UPDATE ZUBME_T007 ##WARN_OK.
    ELSE.
    INSERT ZUBME_T007 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZUBME_V007-UPD_FLAG,
STATUS_ZUBME_V007-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZUBME_V007.
  SELECT SINGLE * FROM ZUBME_T007 WHERE
WERKS = ZUBME_V007-WERKS AND
PROJECT_TYPE = ZUBME_V007-PROJECT_TYPE AND
PROCESS_CODE = ZUBME_V007-PROCESS_CODE AND
ERROR_CODE = ZUBME_V007-ERROR_CODE .
ZUBME_V007-MANDT =
ZUBME_T007-MANDT .
ZUBME_V007-WERKS =
ZUBME_T007-WERKS .
ZUBME_V007-PROJECT_TYPE =
ZUBME_T007-PROJECT_TYPE .
ZUBME_V007-PROCESS_CODE =
ZUBME_T007-PROCESS_CODE .
ZUBME_V007-ERROR_CODE =
ZUBME_T007-ERROR_CODE .
ZUBME_V007-FROM_TO =
ZUBME_T007-FROM_TO .
ZUBME_V007-CC_RECEIVERS =
ZUBME_T007-CC_RECEIVERS .
ZUBME_V007-REC_RECEIVERS =
ZUBME_T007-REC_RECEIVERS .
ZUBME_V007-SO10_TEXT_NAME =
ZUBME_T007-SO10_TEXT_NAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZUBME_V007 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZUBME_V007-WERKS TO
ZUBME_T007-WERKS .
MOVE ZUBME_V007-PROJECT_TYPE TO
ZUBME_T007-PROJECT_TYPE .
MOVE ZUBME_V007-PROCESS_CODE TO
ZUBME_T007-PROCESS_CODE .
MOVE ZUBME_V007-ERROR_CODE TO
ZUBME_T007-ERROR_CODE .
MOVE ZUBME_V007-MANDT TO
ZUBME_T007-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZUBME_T007'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZUBME_T007 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZUBME_T007'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
